name: Generate Snake Animation

on:
  schedule:
    # 每天執行一次
    - cron: "0 0 * * *"
    
  # 允許手動觸發工作流程
  workflow_dispatch:
  
  # 每次推送到 main 分支時運行
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # 生成蛇形動畫
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      
      # 提交生成的文件到 GitHub
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Contribution Snake'